### ISSUE TITLE
I do not think math check out ..

### ISSUE THREAD

**Issue by jeffz2012** [ile/population-calculator#3]
Math in your calculator does not check out.
Your replacement fertility is 2, while in real world it is 2.1 in the west and 2.33 worldwide. It is higher worldwide, as in some countries it can go as high at 3.5 children just to make even, due to many factors like economy, war, poor medical services, lack of education etc.
Nice attempt thou.

**Comment by ile** [comment]
True, 2.1 is the replacement fertility in the real world. 

By "math does no check out" you mean "the graph does not match the real world".

The graph matches an ideal world where mortality is not as high as it is now and males are exactly 50%.

So, the math checks out, but the world isn't ideal.
